name: Check Filtering.md Compliance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-compliance:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        
    - name: Check Filtering.md compliance
      run: |
        echo "🔍 Проверка соблюдения Filtering.md..."
        
        # Проверяем, что нет тестовых файлов
        TEST_FILES=$(find . -name "test-*.php" -o -name "create-test-*.php" -o -name "sample-*.php" -o -name "mock-*.php" | grep -v node_modules | grep -v .git)
        if [ ! -z "$TEST_FILES" ]; then
          echo "❌ Найдены тестовые файлы:"
          echo "$TEST_FILES"
          exit 1
        fi
        
        # Проверяем, что data-api.php не содержит прямых обращений к Airtable
        if grep -q "AirtableDataSource\|getRegionsFromAirtable\|api.airtable.com" api/data-api.php; then
          echo "❌ data-api.php содержит прямые обращения к Airtable"
          exit 1
        fi
        
        # Проверяем, что есть enforce-filtering.php
        if [ ! -f "api/enforce-filtering.php" ]; then
          echo "❌ Отсутствует api/enforce-filtering.php"
          exit 1
        fi
        
        echo "✅ Все проверки пройдены успешно!"
